name: Verify tag signature
on:
  push:
    tags: ["v*"]

jobs:
  verify-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: sudo apt-get update -y && sudo apt-get install -y gnupg
      - run: gpg --import .gpg/MAINTAINERS.asc
      - name: Verify the pushed tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          git verify-tag "$TAG"
